### ISSUE TITLE
How to track the people in the video？

### ISSUE THREAD

**Issue by ywdong** [fan23j/yolov5-vitpose-video-annotator#1]
Greate jobs！ The jobs work fine when video just have one people. If there multiple people in the video，how can I track the one I need？ Great thx.

**Comment by fan23j** [comment]
Are you saying given multiple people in a video, how to extract the inference results of a specific person? If so, you would have to look into object tracking for that. I believe YoloV5 has many open-source implementations so you can modify the detection portion to include tracking. If your videos are relatively simple and you have the meta information on which subject you want, you could potentially use some simple data processing techniques to help with tracking. For example, if you have a video with a subject and people in the background, you could filter detections by bbox size essentially mocking "tracking" because you know the subject will be the largest in frame. Another example is if you know the subject is the first to appear in frame, you could mask out areas around the first bbox to avoid background detections in later frames. But if your videos are more complex, I would look into object tracking algorithms. Again, I am fairly certain YoloV5 already has support for that so hopefully pretty straightforward for you to implement.
