### ISSUE TITLE
Yolov5 model file

### ISSUE THREAD

**Issue by Ared521** [fan23j/yolov5-vitpose-video-annotator#2]
Thank you for your project, I am a novice, I would like to ask which yolov5 model file should be downloaded ?

**Comment by fan23j** [comment]
Since this repo uses yolov5 detector from torch hub, the model weights will be automatically downloaded from torch hub. Currently, the annotation demo uses `yolov5l6` the largest model available. You can change line 119 in `demo/top_down_video_demo_with_yolov5.py` to use whichever yolov5 detector model you want.

**Comment by Ared521** [comment]
> Since this repo uses yolov5 detector from torch hub, the model weights will be automatically downloaded from torch hub. Currently, the annotation demo uses `yolov5l6` the largest model available. You can change line 119 in `demo/top_down_video_demo_with_yolov5.py` to use whichever yolov5 detector model you want.

Thank you for your answer. In video.sh, what should I enter for the parameter --pose-checkpoint?

**Comment by fan23j** [comment]
the path to the downloaded ViTPose model weights.

**Comment by Ared521** [comment]
> the path to the downloaded ViTPose model weights.

OK，Thank you very much.
