### ISSUE TITLE
How to train a custom halpe whobody model

### ISSUE THREAD

**Issue by wanghlsara** [fan23j/yolov5-vitpose-video-annotator#4]
Hi, 
 I download your ViTPose with Halpe [model](https://drive.google.com/file/d/1Ylv9vojQkgpDvYcK6f2BQpyq9vnpR0ve/view?usp=share_link), and it works well. This model(vitpose-halpe-256x192.pth) supports halpe 26 keypoints, but I want 2 more keypoints(one in lefthand, another in righthand, both of which don't have to be very accurate ).  Since  vitpose-halpe-256x192.pth is so big( about 7.5GB),  is it very difficult to train it? or more difficult  for a custom 28 kpts model ? So, Could you give me some advice on how to train it?  or is it a good idea to wait for someone else to share a  hape wholebody model with  hands keypoints?

Looking forward to your reply.

**Comment by fan23j** [comment]
Hello, do your two extra keypoints exist on the coco-wholebody model? Also what is the use-case for this model? If it is just for annotations, you could use an ensemble method to just merge the predictions. A bit inefficient on the inference, but should be less resource than training another model.

**Comment by wanghlsara** [comment]
I use the two extra keypoints to calculate the angle of wrist joint movement. The wrist joint is connected to the hand, so I want to locate one point  to indicate the hand postion, It can be anywhere on the hand, such as the center of the hand box. Can I get the  hand box using your  your ViTPose with Halpe model?

**Comment by fan23j** [comment]
You can use the halpe configuration on the ViTPose repo to train your own custom Halpe model:
https://github.com/ViTAE-Transformer/ViTPose/blob/main/configs/_base_/datasets/halpe.py

Here is the Halpe dataset: https://github.com/Fang-Haoshu/Halpe-FullBody

If you only want the 26 Halpe keypoints + two hand keypoints, you will have to clean the `keypoint_dict` alongside the corresponding `sigmas` in the `halpe.py` dataset config. You will also need to clean the annotations files provided in `Halpe-FullBody`. Otherwise, as long as you have a GPU you should be able to train this model yourself.
